services:
  - type: web
    name: twinpeaks-back
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn twinpeaks.wsgi:application --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DJANGO_SECRET_KEY
        value: ln%%qn5z+^z@4owlm#o%pn=1&_z!*!kv10+rm2qn4$!z)bjy=4
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: twinpeaks-back.onrender.com,localhost
      - key: DATABASE_URL
        fromDatabase:
          name: twinpeaks-sql
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "https://andywhite97.github.io/twinpeaks"
      - key: EMAIL_HOST_USER
        value: your-email@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: your-app-password
      - key: BIRD_API_KEY
        value: your-messagebird-api-key
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
