# Generated by Django 6.0.1 on 2026-02-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
            ],
        ),
    ]
