# Generated by Django 6.0.1 on 2026-06-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("email", models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ("customer_id", models.CharField(editable=False, max_length=20, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "email"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("salesperson", models.CharField(blank=True, max_length=120)),
                ("job", models.CharField(blank=True, max_length=120)),
                ("payment_terms", models.CharField(blank=True, max_length=120)),
                ("tax_rate", models.DecimalField(decimal_places=4, default=0.15, max_digits=5)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("items", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quote", "Quote"),
                            ("invoice", "Invoice"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="quote",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="invoices.customer",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=150)),
                ("product_description", models.TextField(blank=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
