# Generated by Django 6.0.1 on 2026-06-03

import uuid

import django.db.models.deletion
from django.db import migrations, models


def create_customer_records(apps, schema_editor):
    Customer = apps.get_model("invoices", "Customer")
    Invoice = apps.get_model("invoices", "Invoice")

    for invoice in Invoice.objects.all():
        email = (invoice.customer_email or "").strip().lower()
        if not email:
            email = f"invoice-{invoice.pk}@missing.twinpeaks.local"

        customer, _created = Customer.objects.get_or_create(
            email=email,
            defaults={
                "customer_id": generate_customer_id(Customer),
                "name": invoice.customer_name or "Unknown Customer",
                "location": invoice.customer_location or "",
                "phone": invoice.customer_phone or "",
            },
        )
        invoice.customer_id = customer.email

        if invoice.status == "draft":
            invoice.status = "quote"
        elif invoice.status == "sent":
            invoice.status = "invoice"

        invoice.save(update_fields=["customer", "status"])


def generate_customer_id(Customer):
    while True:
        customer_id = f"CUST-{uuid.uuid4().hex[:8].upper()}"
        if not Customer.objects.filter(customer_id=customer_id).exists():
            return customer_id


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="customer_id",
            new_name="legacy_customer_id",
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("email", models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ("customer_id", models.CharField(editable=False, max_length=20, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "email"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="invoices.customer",
            ),
        ),
        migrations.RunPython(create_customer_records, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="invoice",
            name="legacy_customer_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="customer_location",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="customer_email",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="customer_phone",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="invoices.customer",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("quote", "Quote"),
                    ("invoice", "Invoice"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="quote",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=150)),
                ("product_description", models.TextField(blank=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
