# Generated by Django 6.0.1 on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


def copy_invoice_item_links(apps, schema_editor):
    InvoiceItem = apps.get_model("invoices", "InvoiceItem")

    for item in InvoiceItem.objects.exclude(invoice_id=None).iterator():
        item.invoice.items.add(item)


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_customers_invoice_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="items",
            new_name="legacy_items",
        ),
        migrations.AddField(
            model_name="invoice",
            name="items",
            field=models.ManyToManyField(
                blank=True,
                related_name="invoices",
                to="invoices.invoiceitem",
            ),
        ),
        migrations.RunPython(copy_invoice_item_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="legacy_items",
        ),
    ]
