# Generated by Django 6.0.1 on 2026-06-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoiceitem_line_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
    ]
