# Generated by Django 6.0.1 on 2026-06-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoice_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='invoices.invoiceitem'),
        ),
    ]
