# Generated by Django 6.0.1 on 2026-06-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
    ]
