# Generated by Django 6.0.1 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0009_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
