# Generated by Django 6.0.1 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0011_invoice_invoice_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_workbook",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
