# Generated by Django 6.0.1 on 2026-04-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
