# Generated by Django 6.0.1 on 2026-08-13

from django.db import migrations, models


def populate_brand_slugs(apps, schema_editor):
    Brand = apps.get_model("homepage", "Brand")
    for brand in Brand.objects.all():
        brand.slug = f"brand-{brand.pk}"
        brand.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_project_images_and_details"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS homepage_brand_slug_ac37270a_like;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.SlugField(blank=True, db_index=False, null=True),
        ),
        migrations.RunPython(populate_brand_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.RemoveField(
            model_name="brand",
            name="website",
        ),
    ]
