# Generated by Django 6.0.1 on 2026-08-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_brand_slug_remove_brand_website"),
        ("products", "0002_product_categories_and_commerce_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="products", to="homepage.brand"),
        ),
    ]
